In [1]:
%load_ext autoreload
%autoreload 2

from IPython.display import Image
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

import os
import json
import numpy as onp
import jax
import jax.numpy as jnp
import flax
import pickle
import matplotlib.pyplot as plt
import pandas as pd
import torch
import matplotlib
import timecast as tc

from mpl_toolkits import mplot3d


plt.rcParams['figure.figsize'] = [20, 10]

import tqdm.notebook as tqdm

In [2]:
from timecast.utils.statistics import OnlineStatistics
from timecast.utils.gram import OnlineGram

In [3]:
n = 2
X_dim = 1
Y_dim = 1

X = onp.random.rand(n, X_dim)
Y = onp.random.rand(n, Y_dim)

gram = OnlineGram(X_dim, Y_dim)
X_stats = OnlineStatistics(X_dim)
Y_stats = OnlineStatistics(Y_dim)
X_stats.update(X)
Y_stats.update(Y)
gram.update(X, Y)

/home/dsuo/miniconda3/envs/toy_flood/lib/python3.7/site-packages/jax/lib/xla_bridge.py:123: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')


In [4]:
gram.matrix

DeviceArray([[0.03265379]], dtype=float32)

In [5]:
gram.normalize(X_stats, Y_stats)

In [7]:
gram.matrix

DeviceArray([[-2.0000002]], dtype=float32)

In [8]:
X = (X - X.mean(axis=0)) / X.std(axis=0)
Y = (Y - Y.mean(axis=0)) / Y.std(axis=0)

In [9]:
X = jnp.hstack((jnp.ones((n, 1)), X))

In [10]:
X

DeviceArray([[ 1.,  1.],
             [ 1., -1.]], dtype=float32)

In [11]:
Y

array([[-1.],
       [ 1.]])

In [12]:
X.T @ Y

DeviceArray([[ 0.],
             [-2.]], dtype=float32)

In [16]:
a = onp.random.rand(10, 5)

In [17]:
a

array([[0.84307673, 0.44538774, 0.42564643, 0.12171491, 0.88917183],
       [0.77394743, 0.7646017 , 0.33258253, 0.92138299, 0.30430608],
       [0.02256743, 0.86866293, 0.6609633 , 0.77812271, 0.1161298 ],
       [0.98463196, 0.57034055, 0.16921525, 0.54362942, 0.67876194],
       [0.18814693, 0.52813553, 0.62338625, 0.8693166 , 0.11905956],
       [0.46655804, 0.12627905, 0.33611238, 0.17416525, 0.90686794],
       [0.51386906, 0.10408866, 0.07109459, 0.47064581, 0.24981696],
       [0.0715508 , 0.7583042 , 0.59364504, 0.99702378, 0.19686561],
       [0.26149575, 0.06673112, 0.57965947, 0.28058778, 0.70706153],
       [0.04514392, 0.14399364, 0.37822156, 0.09968516, 0.84191029]])

In [18]:
sum = a.sum(axis=0)
mean = a.mean(axis=0)
std = a.std(axis=0)

In [19]:
a = (a - mean) / std

In [20]:
a.sum(axis=0)

array([ 1.11022302e-15,  1.55431223e-15, -2.22044605e-16,  2.22044605e-15,
       -1.11022302e-15])

In [21]:
(sum - mean) / std

array([11.15361863, 13.48349624, 19.89140622, 14.31426267, 14.30176174])

In [22]:
gram.intercept(X_stats, Y_stats, normalize=True)

In [23]:
gram.matrix

DeviceArray([[ 0.       ],
             [-2.0000002]], dtype=float32)